# Generated by Django 3.2 on 2024-10-06 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username contains invalid characters', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
