MIN_SCORE = 1
MAX_SCORE = 10
DEFAULT_SCORE = None

ADMIN = "admin"
MODERATOR = "moderator"
USER = "user"
WRONGUSERNAME = 'me'
REGEXUSERNAME = r'^[\w.@+-]+$'
MAX_LEN_USERNAME = 150
MAX_LEN_EMAIL = 254
MAX_LEN_CHARFIELD = 256
MAX_LEN_OUT = 20
