# Generated by Django 3.2 on 2024-10-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categorie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categorie',
            new_name='category',
        ),
    ]
