# Generated by Django 3.2 on 2024-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
